-- MySQL Script generated by MySQL Workbench
-- Mon Mar 28 11:37:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(15) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Sexo` ENUM('Hombre', 'Mujer', 'Sin especificar') NULL,
  `Calle` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Piso` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NULL,
  `Edad` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BandejaEntrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BandejaEntrada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BandejaEntrada` (
  `idBandejaEntrada` INT NOT NULL AUTO_INCREMENT,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`idBandejaEntrada`, `Usuario_ID`),
  INDEX `fk_BandejaEntrada_Usuario_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_BandejaEntrada_Usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `Texto` VARCHAR(500) NULL,
  `FechaEnvio` DATE NULL,
  `BandejaEntrada_idBandejaEntrada` INT NOT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`idMensaje`, `BandejaEntrada_idBandejaEntrada`, `Usuario_ID`),
  INDEX `fk_Mensaje_BandejaEntrada1_idx` (`BandejaEntrada_idBandejaEntrada` ASC) VISIBLE,
  INDEX `fk_Mensaje_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Mensaje_BandejaEntrada1`
    FOREIGN KEY (`BandejaEntrada_idBandejaEntrada`)
    REFERENCES `mydb`.`BandejaEntrada` (`idBandejaEntrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estadisticas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estadisticas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estadisticas` (
  `idEstadisticas` INT NOT NULL AUTO_INCREMENT,
  `consulta` VARCHAR(45) NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`idEstadisticas`, `Usuario_ID`),
  INDEX `fk_Estadisticas_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Estadisticas_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grupos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grupos` (
  `idGrupos` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idGrupos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favoritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favoritos` (
  `idFavoritos` INT NOT NULL AUTO_INCREMENT,
  `Categoria_idCategoria` INT NOT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`idFavoritos`, `Categoria_idCategoria`, `Usuario_ID`),
  INDEX `fk_Favoritos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Favoritos_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Favoritos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio_salida` DOUBLE NULL,
  `url_foto` VARCHAR(45) NULL,
  `Puja_minima` DOUBLE NULL,
  `Fecha_inicio` DATE NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `Usuario_ID`),
  INDEX `fk_Productos_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Puja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Puja` (
  `idPuja` INT NOT NULL AUTO_INCREMENT,
  `Puja_actual` DOUBLE NULL,
  `Usuario_ID` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idPuja`, `Usuario_ID`, `Productos_idProductos`),
  INDEX `fk_Puja_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  INDEX `fk_Puja_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Puja_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puja_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `Rol` ENUM('Comprador', 'Vendedor', 'Analista', 'Marketing', 'Administrador') NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario_Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_Roles` (
  `Usuario_ID` INT NOT NULL,
  `Roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Roles_idRoles`),
  INDEX `fk_Usuario_has_Roles_Roles1_idx` (`Roles_idRoles` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Roles_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Roles_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Roles_Roles1`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `mydb`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria_Productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_Productos` (
  `Categoria_idCategoria` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`Categoria_idCategoria`, `Productos_idProductos`),
  INDEX `fk_Categoria_has_Productos_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grupo_Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grupo_Usuario` (
  `Grupos_idGrupos` INT NOT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`Grupos_idGrupos`, `Usuario_ID`),
  INDEX `fk_Grupos_has_Usuario_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  INDEX `fk_Grupos_has_Usuario_Grupos1_idx` (`Grupos_idGrupos` ASC) VISIBLE,
  CONSTRAINT `fk_Grupos_has_Usuario_Grupos1`
    FOREIGN KEY (`Grupos_idGrupos`)
    REFERENCES `mydb`.`Grupos` (`idGrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupos_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
